colorScheme = "fire"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = false

replyByEmail = false

# mainSections = ["section1", "section2"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false


[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  recentHeading = "Latest Stories"
  profileAlt = "Siyad Salam"
  profileSubtitle = "DevOps Engineer | India & Poland Stories"
  homepageImage = "img/cover.png" 

[article]
  showDate = true
  showAuthor = true
  showComments = true
  showBreadcrumbs = true
  showDraftLabel = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  taxonomies = ["tags", "categories"]

[list]
  showHero = true
  heroStyle = "basic"
  showBreadcrumbs = true
  showTableOfContents = true

[term]
  showHero = true
  heroStyle = "basic"
  showBreadcrumbs = true
  showTableOfContents = true

[header]
  layout = "fixed"
  sticky = true
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true
  copyrightText = "Â© {year} Your Name. All rights reserved."

[posthogAnalytics]
  apiKey = "phc_lhvE7ohuFrNFfpCsyNDQRZxOzCpfL515XudMQVID9ol"
  host = "https://us.i.posthog.com"
  defaults = "2025-05-24"
  personProfiles = "identified_only"  # or 'always' to create profiles for anonymous users
  capturePageview = true
  capturePageleave = true
  disableSessionRecording = false  # Session recording enabled
